# Generated by Django 2.0.5 on 2018-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('secretary', 'SECRETARY')], default='student', max_length=10),
        ),
    ]
