# Generated by Django 2.0.5 on 2018-06-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edu_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.EduProject'),
        ),
        migrations.AddField(
            model_name='user',
            name='gra_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.GraProject'),
        ),
        migrations.AddField(
            model_name='user',
            name='srtp_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.SRTPProject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('secretary', 'SECRETARY'), ('student', 'STUDENT'), ('teacher', 'TEACHER')], default='student', max_length=10),
        ),
    ]
