# Generated by Django 2.0.5 on 2018-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180610_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('secretary', 'SECRETARY'), ('student', 'STUDENT')], default='student', max_length=10),
        ),
    ]
