# Generated by Django 2.0.5 on 2018-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180615_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('secretary', 'SECRETARY'), ('student', 'STUDENT'), ('teacher', 'TEACHER')], default='student', max_length=10),
        ),
    ]
