# Generated by Django 2.0.5 on 2018-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180610_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('secretary', 'SECRETARY'), ('teacher', 'TEACHER')], default='student', max_length=10),
        ),
    ]
