# Generated by Django 2.0.5 on 2018-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180614_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='佚名', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('student', 'STUDENT'), ('secretary', 'SECRETARY')], default='student', max_length=10),
        ),
    ]
