# Generated by Django 2.0.5 on 2018-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180615_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('secretary', 'SECRETARY'), ('student', 'STUDENT')], default='student', max_length=10),
        ),
    ]
