# Generated by Django 2.0.5 on 2018-06-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180616_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('secretary', 'SECRETARY'), ('teacher', 'TEACHER'), ('student', 'STUDENT')], default='student', max_length=10),
        ),
    ]
