# Generated by Django 2.0.5 on 2018-06-10 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pro_state', models.CharField(choices=[('postponed', 'POSTPONED'), ('abandoned', 'ABANDONED'), ('running', 'RUNNING'), ('done', 'DONE')], default='running', max_length=10)),
                ('pro_level', models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='File_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_url', models.CharField(max_length=50)),
                ('file_type', models.CharField(choices=[('docx/doc', 'DOC'), ('all', 'ALL'), ('excel', 'EXCEL'), ('rar', 'RAR')], default='all', max_length=10)),
                ('pro_stage', models.CharField(choices=[('initial', 'INIT'), ('final', 'FIN'), ('midterm', 'MID')], default='initial', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GraProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRTPProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pro_state', models.CharField(choices=[('postponed', 'POSTPONED'), ('abandoned', 'ABANDONED'), ('running', 'RUNNING'), ('done', 'DONE')], default='running', max_length=10)),
                ('pro_level', models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='file_info',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.SRTPProject'),
        ),
    ]
