# Generated by Django 2.0.5 on 2018-06-14 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('pro_state', models.CharField(choices=[('done', 'DONE'), ('postponed', 'POSTPONED'), ('running', 'RUNNING'), ('abandoned', 'ABANDONED')], default='running', max_length=10)),
                ('pro_level', models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10)),
                ('file1', models.FileField(upload_to='')),
                ('file2', models.FileField(upload_to='')),
                ('file3', models.FileField(upload_to='')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('file1', models.FileField(upload_to='')),
                ('file2', models.FileField(upload_to='')),
                ('file3', models.FileField(upload_to='')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_gra', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_gra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SRTPProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('pro_state', models.CharField(choices=[('done', 'DONE'), ('postponed', 'POSTPONED'), ('running', 'RUNNING'), ('abandoned', 'ABANDONED')], default='running', max_length=10)),
                ('pro_level', models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10)),
                ('file1', models.FileField(upload_to='')),
                ('file2', models.FileField(upload_to='')),
                ('file3', models.FileField(upload_to='')),
                ('students', models.ManyToManyField(related_name='students_srtp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
