# Generated by Django 2.0.5 on 2018-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_info',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file_info',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='file_info',
            name='file_url',
        ),
        migrations.AddField(
            model_name='file_info',
            name='file',
            field=models.FileField(null=True, upload_to='2018/06/10'),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('院级', 'COLLEGE'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('postponed', 'POSTPONED'), ('done', 'DONE'), ('running', 'RUNNING'), ('abandoned', 'ABANDONED')], default='running', max_length=10),
        ),
        migrations.AlterField(
            model_name='file_info',
            name='pro_stage',
            field=models.CharField(choices=[('final', 'FIN'), ('midterm', 'MID'), ('initial', 'INIT')], default='initial', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('院级', 'COLLEGE'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('postponed', 'POSTPONED'), ('done', 'DONE'), ('running', 'RUNNING'), ('abandoned', 'ABANDONED')], default='running', max_length=10),
        ),
    ]
