# Generated by Django 2.0.5 on 2018-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduproject',
            name='file4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='graproject',
            name='file4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='graproject',
            name='file5',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='srtpproject',
            name='file4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('apply_passed', 'APPLY_PASSED'), ('done', 'DONE'), ('apllying', 'APPLYING'), ('final_checking', 'FINAL_CHEKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('END', 'END'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('postponed', 'POSTPONED'), ('end_unconfirmed', 'END_UNCONFIRMED')], default='apllying', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('apply_passed', 'APPLY_PASSED'), ('done', 'DONE'), ('apllying', 'APPLYING'), ('final_checking', 'FINAL_CHEKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('END', 'END'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('postponed', 'POSTPONED'), ('end_unconfirmed', 'END_UNCONFIRMED')], default='apllying', max_length=10),
        ),
    ]
