# Generated by Django 2.0.5 on 2018-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('国家推荐级', 'NATIONALPROMOTED'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('done', 'DONE'), ('postponed', 'POSTPONED'), ('abandoned', 'ABANDONED'), ('running', 'RUNNING')], default='running', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('国家推荐级', 'NATIONALPROMOTED'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('done', 'DONE'), ('postponed', 'POSTPONED'), ('abandoned', 'ABANDONED'), ('running', 'RUNNING')], default='running', max_length=10),
        ),
    ]
