# Generated by Django 2.0.5 on 2018-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('running', 'RUNNING'), ('apllying', 'APPLYING'), ('apply_passed', 'APPLY_PASSED'), ('midterm_passed', 'MIDTERM_PASSED'), ('done', 'DONE'), ('abandoned', 'ABANDONED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('postponed', 'POSTPONED')], default='apllying', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('running', 'RUNNING'), ('apllying', 'APPLYING'), ('apply_passed', 'APPLY_PASSED'), ('midterm_passed', 'MIDTERM_PASSED'), ('done', 'DONE'), ('abandoned', 'ABANDONED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('postponed', 'POSTPONED')], default='apllying', max_length=10),
        ),
    ]
