# Generated by Django 2.0.5 on 2018-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20180615_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='file1',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='file2',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='file3',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='file4',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('院级', 'COLLEGE'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('apply_passed', 'APPLY_PASSED'), ('midterm_passed', 'MIDTERM_PASSED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('done', 'DONE'), ('postponed', 'POSTPONED'), ('end_unconfirmed', 'END_UNCONFIRMED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('END', 'END'), ('final_checking', 'FINAL_CHEKING'), ('unconfirmed', 'UNCONFIRMED')], default='unconfirmed', max_length=10),
        ),
        migrations.AlterField(
            model_name='graproject',
            name='file1',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='graproject',
            name='file2',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='graproject',
            name='file3',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='graproject',
            name='file4',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='graproject',
            name='file5',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='file1',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='file2',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='file3',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='file4',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('院级', 'COLLEGE'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('apply_passed', 'APPLY_PASSED'), ('midterm_passed', 'MIDTERM_PASSED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('done', 'DONE'), ('postponed', 'POSTPONED'), ('end_unconfirmed', 'END_UNCONFIRMED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('END', 'END'), ('final_checking', 'FINAL_CHEKING'), ('unconfirmed', 'UNCONFIRMED')], default='unconfirmed', max_length=10),
        ),
    ]
