# Generated by Django 2.0.5 on 2018-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20180614_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('院级', 'COLLEGE'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('running', 'RUNNING'), ('postponed', 'POSTPONED'), ('done', 'DONE'), ('abandoned', 'ABANDONED')], default='running', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('院级', 'COLLEGE'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('running', 'RUNNING'), ('postponed', 'POSTPONED'), ('done', 'DONE'), ('abandoned', 'ABANDONED')], default='running', max_length=10),
        ),
    ]
