# Generated by Django 2.0.5 on 2018-06-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20180616_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graproject',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('terminate_unconfirmed', 'TERMINATE_UNCONFIRMED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('8', 'TERMINATED'), ('7', 'DONE'), ('6', 'FINAL_CHEKING'), ('5', 'POSTPONED'), ('4', 'FINALTERM'), ('3', 'MIDTERM_CHECKING'), ('2', 'MIDTERM'), ('1', 'UNCONFIRMED')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('terminate_unconfirmed', 'TERMINATE_UNCONFIRMED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('8', 'TERMINATED'), ('7', 'DONE'), ('6', 'FINAL_CHEKING'), ('5', 'POSTPONED'), ('4', 'FINALTERM'), ('3', 'MIDTERM_CHECKING'), ('2', 'MIDTERM'), ('1', 'UNCONFIRMED')], default='1', max_length=10),
        ),
    ]
