# Generated by Django 2.0.5 on 2018-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20180610_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('院级', 'COLLEGE'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('running', 'RUNNING'), ('abandoned', 'ABANDONED'), ('done', 'DONE'), ('postponed', 'POSTPONED')], default='running', max_length=10),
        ),
        migrations.AlterField(
            model_name='file_info',
            name='pro_stage',
            field=models.CharField(choices=[('midterm', 'MID'), ('final', 'FIN'), ('initial', 'INIT')], default='initial', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('院级', 'COLLEGE'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('running', 'RUNNING'), ('abandoned', 'ABANDONED'), ('done', 'DONE'), ('postponed', 'POSTPONED')], default='running', max_length=10),
        ),
    ]
