# Generated by Django 2.0.5 on 2018-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_auto_20180615_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('院级', 'COLLEGE'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('final_checking', 'FINAL_CHEKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('END', 'END'), ('done', 'DONE'), ('apply_passed', 'APPLY_PASSED'), ('end_unconfirmed', 'END_UNCONFIRMED'), ('postponed', 'POSTPONED'), ('unconfirmed', 'UNCONFIRMED')], default='unconfirmed', max_length=10),
        ),
        migrations.AlterField(
            model_name='graproject',
            name='file1',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('院级', 'COLLEGE'), ('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('midterm_checking', 'MIDTERM_CHECKING'), ('final_checking', 'FINAL_CHEKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('END', 'END'), ('done', 'DONE'), ('apply_passed', 'APPLY_PASSED'), ('end_unconfirmed', 'END_UNCONFIRMED'), ('postponed', 'POSTPONED'), ('unconfirmed', 'UNCONFIRMED')], default='unconfirmed', max_length=10),
        ),
    ]
