# Generated by Django 2.0.5 on 2018-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_auto_20180615_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('postponed', 'POSTPONED'), ('done', 'DONE'), ('terminated', 'TERMINATED'), ('apply_passed', 'APPLY_PASSED'), ('final_checking', 'FINAL_CHEKING'), ('midterm_checking', 'MIDTERM_CHECKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('terminate_unconfirmed', 'TERMINATE_UNCONFIRMED'), ('unconfirmed', 'UNCONFIRMED')], default='unconfirmed', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_level',
            field=models.CharField(choices=[('市级推荐级', 'MUNICIPALPROMOTED'), ('国家推荐级', 'NATIONALPROMOTED'), ('院级', 'COLLEGE')], default='院级', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('postponed', 'POSTPONED'), ('done', 'DONE'), ('terminated', 'TERMINATED'), ('apply_passed', 'APPLY_PASSED'), ('final_checking', 'FINAL_CHEKING'), ('midterm_checking', 'MIDTERM_CHECKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('terminate_unconfirmed', 'TERMINATE_UNCONFIRMED'), ('unconfirmed', 'UNCONFIRMED')], default='unconfirmed', max_length=10),
        ),
    ]
