# Generated by Django 2.0.5 on 2018-06-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_auto_20180616_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='pro_state',
            field=models.CharField(choices=[('midterm_checking', 'MIDTERM_CHECKING'), ('terminate_unconfirmed', 'TERMINATE_UNCONFIRMED'), ('apply_passed', 'APPLY_PASSED'), ('terminated', 'TERMINATED'), ('final_checking', 'FINAL_CHEKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('postponed', 'POSTPONED'), ('unconfirmed', 'UNCONFIRMED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('done', 'DONE')], default='unconfirmed', max_length=10),
        ),
        migrations.AlterField(
            model_name='srtpproject',
            name='pro_state',
            field=models.CharField(choices=[('midterm_checking', 'MIDTERM_CHECKING'), ('terminate_unconfirmed', 'TERMINATE_UNCONFIRMED'), ('apply_passed', 'APPLY_PASSED'), ('terminated', 'TERMINATED'), ('final_checking', 'FINAL_CHEKING'), ('midterm_passed', 'MIDTERM_PASSED'), ('postponed', 'POSTPONED'), ('unconfirmed', 'UNCONFIRMED'), ('postpone_unconfirmed', 'POSTPONE_UNCONFIRMED'), ('done', 'DONE')], default='unconfirmed', max_length=10),
        ),
    ]
