# Generated by Django 2.0.5 on 2018-06-14 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('room_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_period_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('reject_class_room', models.ManyToManyField(blank=True, default=None, to='course_arrangement.ClassRoom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.ClassRoom')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='course_arrangement.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('section', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.IntegerField(choices=[(3, 'ACCEPT'), (2, 'MEDIOCRE'), (1, 'LEAST'), (-10, 'REJECT'), (5, 'MOST'), (4, 'SECOND')], default=2)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.Lecture')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('week', 'day', 'section')},
        ),
        migrations.AddField(
            model_name='lecture',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.Period'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='course_arrangement.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('classroom', 'period')},
        ),
    ]
