# Generated by Django 2.0.5 on 2018-06-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(1, 'LEAST'), (2, 'MEDIOCRE'), (4, 'SECOND'), (5, 'MOST'), (3, 'ACCEPT'), (-10, 'REJECT')], default=2),
        ),
    ]
