# Generated by Django 2.0.5 on 2018-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(2, 'MEDIOCRE'), (3, 'ACCEPT'), (-10, 'REJECT'), (4, 'SECOND'), (1, 'LEAST'), (5, 'MOST')], default=2),
        ),
    ]
