# Generated by Django 2.0.5 on 2018-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(3, 'ACCEPT'), (2, 'MEDIOCRE'), (5, 'MOST'), (-10, 'REJECT'), (4, 'SECOND'), (1, 'LEAST')], default=2),
        ),
    ]
