# Generated by Django 2.0.5 on 2018-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0002_auto_20180610_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(4, 'SECOND'), (-10, 'REJECT'), (2, 'MEDIOCRE'), (1, 'LEAST'), (5, 'MOST'), (3, 'ACCEPT')], default=2),
        ),
    ]
