# Generated by Django 2.0.5 on 2018-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0002_auto_20180615_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(-10, 'REJECT'), (3, 'ACCEPT'), (2, 'MEDIOCRE'), (5, 'MOST'), (1, 'LEAST'), (4, 'SECOND')], default=2),
        ),
    ]
