# Generated by Django 2.0.5 on 2018-06-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0002_auto_20180614_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day1',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of Monday'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day2',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of Tuesday'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day3',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of Wednesday'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day4',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of Thursday'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day5',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of Friday'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slot1',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of time slot 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slot2',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of time slot 2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slot3',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of time slot 3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slot4',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of time slot 4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slot5',
            field=models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference of time slot 5'),
        ),
    ]
