# Generated by Django 2.0.5 on 2018-06-14 22:59

import course_arrangement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0003_auto_20180614_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.ClassRoom')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='end_week',
            field=models.IntegerField(validators=[course_arrangement.models.validate_week]),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_week',
            field=models.IntegerField(validators=[course_arrangement.models.validate_week]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.Course'),
        ),
    ]
