# Generated by Django 2.0.5 on 2018-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0003_auto_20180615_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(5, 'MOST'), (2, 'MEDIOCRE'), (3, 'ACCEPT'), (4, 'SECOND'), (-10, 'REJECT'), (1, 'LEAST')], default=2),
        ),
    ]
