# Generated by Django 2.0.5 on 2018-06-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0004_auto_20180614_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
