# Generated by Django 2.0.5 on 2018-06-16 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0005_auto_20180615_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomCollegeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference certain college')),
                ('refer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomFloorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(10, 'HARD_ACCEPT'), (5, 'SOFT_ACCEPT_5'), (4, 'SOFT_ACCEPT_4'), (3, 'SOFT_ACCEPT_3'), (2, 'SOFT_ACCEPT_2'), (1, 'SOFT_ACCEPT_1'), (0, 'SOFT_MEDIOCRE'), (-1, 'SOFT_REJECT_1'), (-2, 'SOFT_REJECT_2'), (-3, 'SOFT_REJECT_3'), (-4, 'SOFT_REJECT_4'), (-5, 'SOFT_REJECT_5'), (-10, 'HARD_REJECT')], default=0, help_text='preference certain floor')),
                ('refer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.ClassRoom')),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['is_lab']},
        ),
        migrations.AddField(
            model_name='course',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slots_per_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='college_preference',
            field=models.ManyToManyField(to='course_arrangement.ClassRoomCollegeChoice'),
        ),
        migrations.AddField(
            model_name='course',
            name='floor_preference',
            field=models.ManyToManyField(to='course_arrangement.ClassRoomFloorChoice'),
        ),
    ]
