# Generated by Django 2.0.5 on 2018-06-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0005_auto_20180616_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='favorite',
            field=models.IntegerField(choices=[(3, 'ACCEPT'), (2, 'MEDIOCRE'), (1, 'LEAST'), (5, 'MOST'), (-10, 'REJECT'), (4, 'SECOND')], default=2),
        ),
    ]
