# Generated by Django 2.0.5 on 2018-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0006_auto_20180616_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='college_preference',
            field=models.ManyToManyField(blank=True, to='course_arrangement.ClassRoomCollegeChoice'),
        ),
        migrations.AlterField(
            model_name='course',
            name='floor_preference',
            field=models.ManyToManyField(blank=True, to='course_arrangement.ClassRoomFloorChoice'),
        ),
    ]
